I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 485, in script
    show char serena bad
Exception: Image 'char serena' does not accept attributes 'bad'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 485, in script
    show char serena bad
  File "C:\Users\highl\Desktop\RENPY\renpy-8.2.3-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\highl\Desktop\RENPY\renpy-8.2.3-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\highl\Desktop\RENPY\renpy-8.2.3-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\highl\Desktop\RENPY\renpy-8.2.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\highl\Desktop\RENPY\renpy-8.2.3-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\highl\Desktop\RENPY\renpy-8.2.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'char serena' does not accept attributes 'bad'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Vertical Android 1.0
Sat Aug 24 21:44:29 2024
